### ISSUE TITLE
Black Belt hangs with mockingboard

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4sports#23] opened 2022-12-19 08:14 UTC
Seems to be waiting for an interrupt from the mockingboard or speech chip? Bug seems to be present in the original WOZ file as well.

Hangs during demo at the end of the round, and at the end of a game round.

Mockingboard could also auto-configure, if so inclined. Currently asks whether a card is installed.

**Comment by peterferrie** [comment] 2022-12-19 19:00
I can't reproduce it in AppleWin.  Please share a save-state if it's in an emulator.

**Comment by tomcw** [comment] 2022-12-20 21:36
Under AppleWin, this [woz](https://archive.org/details/wozaday_Black_Belt) seems to hang on track 13 ($0D) as @frankmilliron describes.
Although at first glance it appears to be disk related (not MB/IRQ related), but I've not dug into it.

NB. the "black belt PRODOS (san inc pack).dsk" works fine.

**Comment by frankmilliron** [comment] 2022-12-20 21:42
I've been working on a demo for this, but haven't gotten far enough along the code to figure out how to repro. I think it was at the very end of the "3. DEMO" routine but I may have seen it in the actual gameplay too.

**Comment by peterferrie** [comment] 2022-12-20 21:46
T13 hang is while trying to write out stats.  The woz is
write-protected, and the game loops retries infinitely on error.

**Comment by peterferrie** [comment] 2023-09-29 03:19
mockingboard hang is fixed in 657cb6c9f1ca26d7ceaa691917ac25576c69d85b, using the entirely new version

**Closed as completed by peterferrie** 2023-09-29 03:19 UTC
