### ISSUE TITLE
Championship Baseball fails to load

### ISSUE THREAD

**Issue by frankmilliron** [a2-4am/4sports#9] opened 2022-08-23 04:49 UTC
Game doesn't seem to want to start in either Virtual II or MAME's //gs emulation.

**Comment by peterferrie** [comment] 2022-08-23 04:55
The cause is understood.  I'm not intercepting its disk access correctly, so it's currently reading from hard-coded locations, and doesn't like the subdirectory.

**Comment by peterferrie** [comment] 2023-10-05 05:58
fixed in 8c39695701f9f4f4aded8ee8f00286fde29f51fe

**Closed as completed by peterferrie** 2023-10-05 05:58 UTC
